### PR TITLE
refactor(webui): better build command

### PR DESCRIPTION
**Pull request by ldez**
- clean before build (mode force)
- update documentation
- update `Makefile`
- remove `static` folder

### CODE REVIEW

**Comment by emilevauge** [comment]
LGTM :)

**Comment by vdemeester** [comment]
LGTM 🐸

**Comment by ldez** [comment]
Merger moi. :mushroom: 
Merger moi. :mushroom: 
Merger moi. :mushroom: 

C'est le cri de la PR qui supplie !

http://www.dailymotion.com/video/x12r33_billy-ze-kick-et-les-gamins-mangez_music

**Comment by vdemeester** [comment]
waay

**Pull request merged**
