### PR TITLE
Add passHostHeader to kv frontend definition.

### LINKED ISSUE #107: passHostHeader with kv backends not working
Release: v1.0.alpha.275

### PR DESCRIPTION
**Pull request by bennyhansson**
Fixes #107

### CODE REVIEW

**Comment by emilevauge** [comment]
Hi @bennyhansson, thanks!
But the documentation should also be updated ;)

**Comment by bennyhansson** [comment]
passHostHeader is already documented in the kv sections.
What part needs updating ?

**Comment by emilevauge** [comment]
Ops! You're right ^^ Then LGTM :)
cc @vdemeester

**Comment by vdemeester** [comment]
LGTM 🐸

**Pull request merged**
