### PR TITLE
support docker TLS client

### PR DESCRIPTION
**Pull request by kmtong**

### CODE REVIEW

**Comment by emilevauge** [comment]
Hi @kmtong, thanks for your contribution!
I would suggest to this way:

```go
// Docker holds configurations of the Docker provider.
type Docker struct {
	Watch    bool
	Endpoint string
	Filename string
	Domain   string
	TLS      *DockerTLS
}

type DockerTLS struct {
	CA       string
	Cert     string
	Key      string
}
```
@vdemeester, what is your thoughts on this ?
Besides, the documentation should be updated @kmtong ;)

**Comment by kmtong** [comment]
It looks more structural.  Great!

**Comment by emilevauge** [comment]
@kmtong thanks for your contribution!
Could you also update https://github.com/emilevauge/traefik/blob/master/traefik.sample.toml?
Other than that it would be OK ;)

**Comment by kmtong** [comment]
Updated accordingly.

**Comment by vdemeester** [comment]
@emilevauge @kmtong there is an option in the docker client which is called `InsecureSkipVerify`, I think we could/should support it also, wdyt ? (`client.TLSConfig.InsecureSkipVerify`)

@kmtong Could you squash your commits to have just one for this PR ? thanks :wink:

**Comment by kmtong** [comment]
Updated, see #120.

**Pull request closed without merging**
