### PR TITLE
Bump go 1.6

### LINKED ISSUE #139: HTTP2 Support
I was just wondering whether HTTP2 support was on the roadmap anywhere? I ask this as I would love to load balance gRPC with Traefik.

### PR DESCRIPTION
**Pull request by emilevauge**
This PR bump to go v1.6 and adds native HTTP2 support :)
Fixes #139

### CODE REVIEW

**Comment by vdemeester** [comment]
:tada:

**Comment by emilevauge** [comment]
And it's green !

**Comment by thaJeztah** [comment]
\o/ the most beautiful color in CI

**Comment by advait** [comment]
⚡⚡⚡⚡

**Comment by vdemeester** [comment]
LGTM 🐯

**Pull request merged**
