### PR TITLE
New dashboard with auto refresh

### PR DESCRIPTION
**Pull request by ldez**
- New dashboard:
  - show providers (auto refresh: 2s)
  - show health (auto refresh: 3s) [NEW]
  - more colors
- Review of API REST
- Documentation review

### CODE REVIEW

**Comment by EmileVauge** [comment]
build failed!

**Comment by EmileVauge** [comment]
:+1: :+1: :+1: This is huge @ldez ! LGTM

**Comment by vdemeester** [comment]
With 0 provider / backend / frontend / … :sweat_smile: 

2015-10-05-234446_1600x900_scrot

**Comment by vdemeester** [comment]
:+1: Looks very good ! :tada: 
LGTM 🐼

**Comment by ldez** [comment]
anigif_enhanced-buzz-1647-1390066440-15

**Pull request merged**
