### PR TITLE
Added benchmarks

### PR DESCRIPTION
**Pull request by EmileVauge**
Early benchmarks added.

### CODE REVIEW

**Comment by vdemeester** [comment]
LGTM ;-)

**Comment by EmileVauge** [comment]
@vdemeester am I dreaming or it's not visible in the master?

**Comment by thaJeztah** [comment]
You're not dreaming; it's not visible; which is weird, because I know I've seen it yesterday. Possibly a GitHub bug? (haven't checked out the repository, as I'm on my phone now)

**Comment by vdemeester** [comment]
@EmileVauge Yeah that's definitly weird.. I'm not seeing commits either.. :sweat:

**Comment by vdemeester** [comment]
Merged it back.. but that's weird.. :sweat:

**Comment by EmileVauge** [comment]
Woah... Scary... Will ping Github on that.
Thanks @vdemeester.

**Comment by vdemeester** [comment]
yeah.. that's a little bit scary indeed ! :screaming_cat:

**Comment by thaJeztah** [comment]
Did you do a force push by accident? (you can now protect against that on GitHub by the way)

**Comment by vdemeester** [comment]
@EmileVauge as @thaJeztah said, I think we should protect the master branch indeed :wink: against us :sweat_smile:

**Comment by EmileVauge** [comment]
Yeah, It's now protected.
I'm sorry it seems to be my fault :cry: 
Github' support said that I forced pushed this commit bbfd6c7257c87298d184d89850801957d3a08f9c but I still don't understand exactly what happened because it comes from a merge from @vdemeester https://github.com/EmileVauge/traefik/pull/23.
```git push --force```

**Pull request merged**
