### PR TITLE
Health graph

### PR DESCRIPTION
**Pull request by ldez**
- add realtime chart
  - Total Status Code Count
  - Average response time
  - D3 & NVD3 & Angular NVD3
- enhance Health API documentation
- homepage link correction (Bower)
- add new screenshot of the web ui

traefik-health

### CODE REVIEW

**Comment by EmileVauge** [comment]
LGTM, nice job @ldez !

**Comment by vdemeester** [comment]
@ldez needs a rebase :sweat_smile:

**Comment by ldez** [comment]
done

**Comment by vdemeester** [comment]
LGTM 🐵

**Pull request merged**
