### PR TITLE
Websockets support

### LINKED ISSUE #8: Support for WebSockets
One major reason why I haven't been able to play with something like vulcand is the lack of WebSocket support. This may not be high on the priority list. But support for WebSockets would make this much more viable to me as a replacement for my more kudgly HAProxy and nginx reverse proxy setups in Docker.

### LINKED ISSUE #56: Simple configuration panics
With current master the following configuration, traefik panics :

```toml
# Reverse proxy port
#
# Optional
# Default: ":80"
#
# port = ":80"
#
# LogLevel
logLevel = "DEBUG"

[file]
```

This is probably because `[file]` is empty (nothing in it) but.. probably should not panic :wink:.

The panics is :

```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x18 pc=0x642e10]

goroutine 9 [running]:
github.com/mailgun/manners.(*GracefulListener).Clone(0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/mailgun/manners/listener.go:105 +0x40
github.com/mailgun/manners.(*GracefulServer).HijackListener(0xc820011700, 0xc820186300, 0x0, 0xc8201544e0, 0x0, 0x0)
        /go/src/github.com/mailgun/manners/server.go:184 +0x46
main.prepareServer(0xc820192500, 0xc82010bad0, 0xc820011700, 0xc8201abec0, 0x2, 0x2, 0x0)
        /go/src/github.com/emilevauge/traefik/traefik.go:234 +0x5a6
main.main.func1(0xc82001ac00, 0xc82010bad0, 0xc82002c110, 0xc82002c108, 0xc82002c120)
        /go/src/github.com/emilevauge/traefik/traefik.go:118 +0x94a
created by main.main
        /go/src/github.com/emilevauge/traefik/traefik.go:131 +0xa7d

goroutine 1 [chan receive]:
main.main()
        /go/src/github.com/emilevauge/traefik/traefik.go:188 +0x14fe

goroutine 5 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 6 [sleep]:                                                                                                 [41/1242]
time.Sleep(0x3b9aca00)
        /usr/local/go/src/runtime/time.go:59 +0xf9
github.com/thoas/stats.New.func1(0xc82001aae0)
        /go/src/github.com/thoas/stats/stats.go:33 +0x2e
created by github.com/thoas/stats.New
        /go/src/github.com/thoas/stats/stats.go:35 +0x161

goroutine 8 [select, locked to thread]:
runtime.gopark(0xc2dc90, 0xc82002b728, 0xb08bc8, 0x6, 0x45b718, 0x2)
        /usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc82002b728, 0x0, 0x18)
        /usr/local/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc82002b728)
        /usr/local/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
        /usr/local/go/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 11 [chan receive]:
main.main.func3(0xc82001ac60, 0xc82002c108, 0xc82001acc0)
        /go/src/github.com/emilevauge/traefik/traefik.go:176 +0x5b
created by main.main
        /go/src/github.com/emilevauge/traefik/traefik.go:181 +0x1348

goroutine 12 [runnable]:
reflect.Value.Type(0xa2a100, 0xc820011728, 0xf3, 0x7f8ec12cf0a8, 0xa2a100)
        /usr/local/go/src/reflect/value.go:1661
github.com/davecgh/go-spew/spew.unsafeReflectValue(0xa2a100, 0xc820011728, 0xf3, 0x0, 0x0, 0x0)
        /go/src/github.com/davecgh/go-spew/spew/bypass.go:112 +0x113
github.com/davecgh/go-spew/spew.handleMethods(0xee5620, 0x7f8ec12cf928, 0xc82012fe30, 0xa2a100, 0xc820011728, 0xf3, 0x0)
        /go/src/github.com/davecgh/go-spew/spew/common.go:97 +0x93
github.com/davecgh/go-spew/spew.(*dumpState).dump(0xc8200afd90, 0xa2a100, 0xc820011728, 0xf3)
        /go/src/github.com/davecgh/go-spew/spew/dump.go:308 +0x490
github.com/davecgh/go-spew/spew.(*dumpState).dump(0xc8200afd90, 0xac5140, 0xc820011700, 0xd9)
        /go/src/github.com/davecgh/go-spew/spew/dump.go:423 +0x18d3
github.com/davecgh/go-spew/spew.(*dumpState).dumpPtr(0xc8200afd90, 0xaceb80, 0xc820011700, 0x16)
        /go/src/github.com/davecgh/go-spew/spew/dump.go:154 +0x759
github.com/davecgh/go-spew/spew.(*dumpState).dump(0xc8200afd90, 0xaceb80, 0xc820011700, 0x16)
        /go/src/github.com/davecgh/go-spew/spew/dump.go:264 +0x120
github.com/davecgh/go-spew/spew.fdump(0xee5620, 0x7f8ec12cf928, 0xc82012fe30, 0xc8200afed0, 0x1, 0x1)
        /go/src/github.com/davecgh/go-spew/spew/dump.go:467 +0x2d0
github.com/davecgh/go-spew/spew.Sdump(0xc8200afed0, 0x1, 0x1, 0x0, 0x0)
        /go/src/github.com/davecgh/go-spew/spew/dump.go:482 +0xaa
main.startServer(0xc820011700, 0xc82010bad0)
        /go/src/github.com/emilevauge/traefik/traefik.go:194 +0x1b1
created by main.main
        /go/src/github.com/emilevauge/traefik/traefik.go:186 +0x14db

goroutine 18 [syscall]:
syscall.Syscall6(0xe8, 0x4, 0xc8201d7c24, 0x7, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.EpollWait(0x4, 0xc8201d7c24, 0x7, 0x7, 0xffffffffffffffff, 0x0, 0x0, 0x0)
        /usr/local/go/src/syscall/zsyscall_linux_amd64.go:365 +0x89
gopkg.in/fsnotify%2ev1.(*fdPoller).wait(0xc82017c000, 0xc2d200, 0x0, 0x0)
        /go/src/gopkg.in/fsnotify.v1/inotify_poller.go:85 +0xbc
gopkg.in/fsnotify%2ev1.(*Watcher).readEvents(0xc820192000)
        /go/src/gopkg.in/fsnotify.v1/inotify.go:179 +0x1af
created by gopkg.in/fsnotify%2ev1.NewWatcher
        /go/src/gopkg.in/fsnotify.v1/inotify.go:58 +0x315
```

### PR DESCRIPTION
**Pull request by EmileVauge**
This PR adds web socket support, only for `wrr` load-balancer for now.

Fixes #8 
Fixes #56.

Magic

### CODE REVIEW

**Comment by vdemeester** [comment]
Build is broken :sweat:.
broken

**Comment by EmileVauge** [comment]
Singing in the rain

**Comment by vdemeester** [comment]
@EmileVauge testing out. Updated the comment to add "Fixes #56" to auto-close the issue :wink:

**Comment by vdemeester** [comment]
Soo... It seems to work :wink: 

```bash
$ docker run -d -l traefik.backend=test -l traefik.host=test emilevauge/whoami
$  wscat -c ws://test.localhost:8000/echo 
connected (press CTRL+C to quit)
> ls
< ls
> echo
< echo
```

no-idea-grandme

**Comment by vdemeester** [comment]
Design & Code LGTM 🐙

**Pull request merged**
