### PR TITLE
New build system for Web UI

### PR DESCRIPTION
**Pull request by ldez**
- use [generator-gulp-angular](https://github.com/Swiip/generator-gulp-angular) by @swiip
- remove old static file
- generate optimised static file

### CODE REVIEW

**Comment by emilevauge** [comment]
Thanks @ldez :) Great!
Could you explain a bit more in the doc what are the entry point files and what is generated (you know, for front end noobs...) ?

**Comment by ldez** [comment]
Done, read and say me if a noobs can understands :wink:

**Comment by emilevauge** [comment]
:+1: thanks @ldez 
LGTM

**Comment by vdemeester** [comment]
I wonder if we should store or not the generated stuff : I mean it could be a step of the build process. 
I definitely would like to be able to change something without having `node` on my computer — maybe we should update the dev' `Dockerfile` to have these dependency in it as well.

But that's just a nit so it LGTM for me, just waiting for your opinion on that before merging :stuck_out_tongue_closed_eyes:.

**Comment by emilevauge** [comment]
As I'm going into vendoring soon, let's store everything into the repo!
But it would be nice to update the global build process as well. @ldez ?

**Comment by ldez** [comment]
I understand and I think about how do this.

**Comment by vdemeester** [comment]
@ldez cool :+1: We could merge as is and waiting for another PR, wdyt @emilevauge @ldez ? :wink:

**Comment by emilevauge** [comment]
Both are ok for me. @ldez, as you wish.

**Comment by ldez** [comment]
I did it !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

ob_819310_tumblr-mswrdcc0ae1s0mokmo1-400

**Comment by emilevauge** [comment]
Thanks a lot @ldez !
LGTM

**Comment by vdemeester** [comment]
LGTM 🐵

**Pull request merged**
