### PR TITLE
Add Marathon TLS client config

### LINKED ISSUE #110: Support Marathon Authentication and SSL key verification
In order to use traefik in secured marathon environments we would like to see traefik support authenticating to marathon. go-marathon support Basic Authentication.

As part of this, we'd like to look into disabling SSL verification (this may be an update in go-marathon).

### PR DESCRIPTION
**Pull request by emilevauge**
This PR adds Marathon TLS client configuration.
Fixes #110

### CODE REVIEW

**Comment by emilevauge** [comment]
@rebaseTraefik

**Comment by rebaseTraefik** [comment]
I just pushed up the changes, enjoy!

**Comment by vdemeester** [comment]
@emilevauge tests are broken, you need to update the *marathon* `fakeClient`.

**Comment by emilevauge** [comment]
Tests are fixed using testify/mocks :)

**Comment by emilevauge** [comment]
@rebaseTraefik

**Comment by rebaseTraefik** [comment]
I just pushed up the changes, enjoy!

**Comment by emilevauge** [comment]
@rebaseTraefik

**Comment by rebaseTraefik** [comment]
I just pushed up the changes, enjoy!

**Comment by vdemeester** [comment]
LGTM 🐰

**Pull request merged**
