### PR TITLE
feat(api): add api routes for Frontend Routes

### PR DESCRIPTION
**Pull request by ldez**
- add `/api/providers/{provider}/frontends/{frontend}/routes`
- add `/api/providers/{provider}/frontends/{frontend}/routes/{route}`
- remove dead Go Templates (previouly Web UI template)

### CODE REVIEW

**Comment by EmileVauge** [comment]
LGTM

**Comment by vdemeester** [comment]
@ldez needs a rebase :sweat_smile:

**Comment by ldez** [comment]
done

**Comment by vdemeester** [comment]
LGTM 🐯

**Pull request merged**
