### PR TITLE
Add mutex around prepareserver

### LINKED ISSUE #125: Concurrency issue with prepareServer
`prepareServer` can have a concurrency issue if a provider calls it before the end of its first call.
cc @janeczku in #121.

### PR DESCRIPTION
**Pull request by emilevauge**
This PR fixes #125 adding a mutex around `prepareserver` calls.
cc @janeczku in #121.

### CODE REVIEW

**Comment by vdemeester** [comment]
I don't like `mutex` :scream_cat:.

catcat

**Comment by emilevauge** [comment]
Yeah, me neither, but sometimes you have to face reality ^^

**Comment by vdemeester** [comment]
ace6

**Comment by vdemeester** [comment]
All right, LGTM :smile_cat:

**Pull request merged**
